name: Deploy to WordPress.org SVN
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: |
          mkdir ../temp_vendor
          composer install --no-dev --optimize-autoloader --working-dir=.
          
          rm -rf vendor/phpunit vendor/sebastian vendor/phar-io vendor/theseer vendor/nikic vendor/myclabs vendor/mockery vendor/hamcrest vendor/doctrine vendor/antecedent vendor/10up
          
          find vendor -type l -delete
          find vendor -type d -name ".git" -exec rm -rf {} +
          find vendor -type d -name ".svn" -exec rm -rf {} +

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: briqpay-for-woocommerce